- project:
    name: openstack/neutron-classifier
    check:
      jobs:
        - openstack-tox-functional
        - openstack-tox-functional-py35
    gate:
      jobs:
        - openstack-tox-functional
        - openstack-tox-functional-py35
