- project:
    check:
      jobs:
        - neutron-classifier-functional-dsvm:
            required-projects:
              - openstack/neutron
    gate:
      jobs:
        - neutron-classifier-functional-dsvm:
            required-projects:
              - openstack/neutron

- job:
    name: neutron-classifier-functional-dsvm
    parent: legacy-dsvm-base, devstack
    pre-run: playbooks/legacy/neutron-classifier-functional-dsvm/pre.yaml
    run: playbooks/legacy/neutron-classifier-functional-dsvm/run.yaml
    post-run: playbooks/legacy/neutron-classifier-functional-dsvm/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
    roles:
      - zuul: openstack-infra/devstack
    vars:
      devstack_localrc:
        LIBS_FROM_GIT: python-openstackclient
        GLANCE_V1_ENABLED: true
    devstack_local_conf:
        post-config:
          $CINDER_CONF:
            DEFAULT:
              enable_v1_api: true
    devstack_services:
        ceilometer-acentral: false
        ceilometer-acompute: false
        ceilometer-alarm-evaluator: false
        ceilometer-alarm-notifier: false
        ceilometer-anotification: false
        ceilometer-api: false
        ceilometer-collector: false
        horizon: false
    osc_environment:
        PYTHONUNBUFFERED: 'true'
        OS_CLOUD: devstack-admin
    tox_install_siblings: false
    zuul_work_dir: src/git.openstack.org/openstack/neutron-classifier
