- project:
    check:
      jobs:
        - openstack-tox-functional:
            required-projects:
              - openstack/neutron
        - openstack-tox-functional-py35:
            required-projects:
              - openstack/neutron
    gate:
      jobs:
        - openstack-tox-functional:
            required-projects:
              - openstack/neutron
        - openstack-tox-functional-py35:
            required-projects:
              - openstack/neutron
