- project:
    check:
      jobs:
        - neutron-classifier-functional-dsvm:
            required-projects:
              - openstack/neutron
        - openstack-tox-functional-py35:
            required-projects:
              - openstack/neutron
    gate:
      jobs:
        -  neutron-classifier-functional-dsvm:
            required-projects:
              - openstack/neutron
        - openstack-tox-functional-py35:
            required-projects:
              - openstack/neutron

- job:
    name: neutron-classifier-functional-dsvm
    run: playbooks/legacy/neutron-classifier-funtional-dsvm/run.yaml
    post-run: playbooks/legacy/neutron-classifier-functional-dsvm/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/neutron-classifier

